name: Update Rules
on: push

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main 
      - name: Githubhosts
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://github.com/hacamer/filtering/raw/master/hosts
          file-name: Githosts.txt 
          
      #- name: Cl
           
      - name: Git push assets to github & coding
        run: |
          #rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          git remote add origin "https://github.com/Cats-Team/Ad-Rules.git"
          git remote set-url --add origin "https://${{ secrets.CODING_TokenUser }}:${{ secrets.CODING_Token }}@e.coding.net/hacamer/adgurd/adrules.git"
          git fetch --unshallow origin
          git push -u -f origin main
          #git push -f
          #git push --set-upstream origin main
  
