name: Update Rules
on: push

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main           
      - name: Clean Versions
        run: |
          bash clean-versions.sh
          echo 'OK!'
      - name: Git push assets to github
        run: |
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add .
          git commit -m "Updated at $(TZ=UTC-8 date +(北京时间)"
          git push -f
 
      - name: Git push assets to github & coding
        run: |
          rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add .
          git commit -m "Updated at $(date)"
          #git remote add origin "https://github.com/Cats-Team/AdRule.git"
          git remote add origin "https://${{ secrets.CODING_TokenUser }}:${{ secrets.CODING_Token }}@e.coding.net/hacamer/adgurd/adrules.git"
          #git fetch --unshallow origin
          git push -u -f origin main
          #git push -f
          #git push --set-upstream origin main
  
